domain: zbitech.local

certificate:
  duration: 8760h
  renewBefore: 730h
  issuer:
    kind: ClusterIssuer
    name: cert-issuer

externalDNS:
  enabled: false

database:
  enabled: true

mongoexpress:
  enabled: true

